### PR TITLE
Fix Consumer PATCH 

### LINKED ISSUE #138: ex fb ads auth not working after premission update via PATCH
Potrebujem upravit permission pre ex fb ads podla navodu v https://sites.google.com/keboola.com/devel-internal/komponenty/oauth/registrovan%C3%A9-oauth-komponenty?authuser=1#h.p_RKY9nri0vIxg a tak
- volam PATCH na `manage/keboola.ex-facebook-ads` a dostavam success vid:
image

- nasledne skusam autorizovat otvorenim https://oauth.keboola.com/authorize/keboola.ex-facebook-ads a dostanem error:
```
{
"errorMessage": "FB API error: [object Object]",
"requestId": "73cef0f5-6f99-48d8-9962-43f5d04c829a"
}
``` 
V papertrail sa nic viac nedozviem  
image
Rovnako to dopadne aj ked skusam oauth cez kbc ui.

Podobny postup ale funguje na starom oauth tj 
- zmenim perms cez PATCH:
image
- skusam autorizovat cez https://syrup.keboola.com/oauth-v2/authorize/keboola.ex-facebook-ads a dostanem token

### Resume
1. Z `FB API error: [object Object]` sa nedozviem sa kde je chyba(ak som ju urobil ja) 
2. Je mozne ze to nejak rozbije PATCH?

### PR DESCRIPTION
**Pull request by MiroCillik**
FIXES #138 

The `app_secret` was being encrypted on save even if it was already encrypted <= Wasn't in the PATCH request body.

### CODE REVIEW

File: src/app/Consumers.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ import Migration from '../lib/Migration';
 
 const tableName = DynamoDB.tableNames().consumers;
 
-const getConsumer = (dynamoDb, encryption, componentId) => dynamoDb.get({
+const getConsumer = (dynamoDb, componentId) => dynamoDb.get({
```
Comment (MiroCillik) [inline src/app/Consumers.js]: Tu som si vsimol, ze je navyse parameter

File: tests/app/Consumers.js [hunk 2]
```diff
@@ -105,12 +105,14 @@ function deleteConsumers() {
...
+  const prefix = 'KMS::encrypted::';
+
   AWS.mock('KMS', 'encrypt', (params, callback) => callback(null, {
-    CiphertextBlob: params.Plaintext,
+    CiphertextBlob: prefix + params.Plaintext,
   }));
 
   AWS.mock('KMS', 'decrypt', (params, callback) => callback(null, {
-    Plaintext: params.CiphertextBlob,
+    Plaintext: params.CiphertextBlob.replace(prefix, ''),
```
Comment (MiroCillik) [inline tests/app/Consumers.js]: Sem som pridal prefix, aby bolo jasne, kedy to je enkryptovane a kedy nie. Preto aj testy prechadzali bez problemov.
